### ISSUE TITLE
Service image not appearing in production build

### ISSUE THREAD

**Issue by marcmarina** [cordada-outdoor/cordada-frontend#12]
The service image in the services list is not rendered **only** in the production build due to it having a **height of 0px.** This has been the case since the cards were first created.

Expected:
![image](https://github.com/user-attachments/assets/7e840032-8289-474a-bc61-7e37d133943e)

Current:
![image](https://github.com/user-attachments/assets/46951cd7-6798-40e6-b6c8-824af09ff3f8)

**Steps to debug**
1. `yarn build`
2. `npx -y serve -s build`
3. Go to http://localhost:3000/services and inspect element.

**Comment by JoanBogunya** [comment]
fixed :)

**Comment by JoanBogunya** [comment]
Fixed :)
